on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest]
        os: [ubuntu-latest]
        node-version: [14.x]

    steps:
      - run: uname -a
      - name: Fetch source code
        uses: actions/checkout@v2
      - name: Use Nix
        uses: cachix/install-nix-action@v12
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configure Nix substituters
        run: mkdir -p ~/.config/nix && cp ./.github/nix.conf ~/.config/nix/
      - name: Prepare Nix environment
        run: nix-shell --command "echo Completed"
      - run: nix-shell --run 'cd tests && npm install'
      - run: nix-shell --run 'cd tests && npm run test:setup'
      - run: nix-shell --run 'cd tests && npm run test:exec'
